spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: jdbc:mysql://localhost:3306/whatssuev2?serverTimezone=UTC&characterEncoding=UTF-8
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
loggin:
  level:
    org:
      apache:
        coyote:
          http11: debug